# Generated by Django 4.0.4 on 2022-05-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_cart_product_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
